apiVersion: v1
kind: Service
metadata:
  name: php-clusterip-svc
  labels:
    app: php 
    app.kubernetes.io/name: php
spec: 
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: php
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10