name: Build and Deploy
on:
  push:
    branches:
      - "main"
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Check Outputs
        run: |
          echo "SHA_SHORT: ${{ env.sha_short }}"
          echo "EFS_ID: ${{ secrets.EFS_ID }}"
          echo "CERT_ARN: ${{ secrets.CERT_ARN }}"
 
      - name: Find and Replace image Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "blood-bank-frontend:latest"
          replace: "blood-bank-frontend:${{ env.sha_short }}"
          include: "Kubernetes/**"
          regex: true 

      - name: Find and Replace efs id
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "fs-0aa27663d48eb2216"
          replace: ${{ secrets.EFS_ID }}
          include: "Kubernetes/**"
          regex: true 
          
      - name: Find and Replace certificate arn
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "arn:aws:acm:us-east-1:898855110204:certificate/f3492c91-8f2e-41a8-8d85-9ec41de7b2b7"
          replace: ${{ secrets.CERT_ARN }}
          include: "Kubernetes/**"
          regex: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build 
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile 
          push: true
          tags: soravkumarsharma/blood-bank-frontend:${{ env.sha_short }}

      - name: Pushes Argo Rollout manifest
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'Kubernetes/php/argo-rollout.yml'
          destination_repo: 'soravkumarsharma/Blood-Bank-Management-System-Infra'
          destination_folder: 'Kubernetes/php/'
          user_email: 'add.sorav@gmail.com'
          user_name: 'Sorav Kumar Sharma'
          commit_message: 'Argo-Rollout manifest updated from CI pipeline'

      - name: Pushes Ingress manifest
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'Kubernetes/php/ingress.yml'
          destination_repo: 'soravkumarsharma/Blood-Bank-Management-System-Infra'
          destination_folder: 'Kubernetes/php/'
          user_email: 'add.sorav@gmail.com'
          user_name: 'Sorav Kumar Sharma'
          commit_message: 'Ingress manifest updated from CI pipeline'

      - name: Pushes Persistent Volume manifest
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'Kubernetes/php/pv.yml'
          destination_repo: 'soravkumarsharma/Blood-Bank-Management-System-Infra'
          destination_folder: 'Kubernetes/php/'
          user_email: 'add.sorav@gmail.com'
          user_name: 'Sorav Kumar Sharma'
          commit_message: 'Persistent Volume manifest updated from CI pipeline'

