name: Build and Deploy
on:
  push:
    branches:
      - "main"
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check Outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Find and Replace image Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "blood-bank-frontend:latest"
          replace: blood-bank-frontend:${{ steps.vars.outputs.sha_short }}
          include: Kubernetes/**
          regex: true 

      - name: Find and Replace efs id
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "fs-0aa27663d48eb2216"
          replace: ${{ env.EFS_ID }}
          include: Kubernetes/**
          regex: true
          
      - name: Find and Replace certificate arn
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "arn:aws:acm:us-east-1:898855110204:certificate/f3492c91-8f2e-41a8-8d85-9ec41de7b2b7"
          replace: ${{ env.CERT_ARN }}
          include: Kubernetes/**
          regex: true

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
          name: Build and push
          id: docker_build 
          uses: docker/build-push-action@v5
          with:
            context: ./
            file: ./Dockerfile 
            push: true
            tags: soravkumarsharma/blood-bank-frontend:${{ steps.vars.outputs.sha_short }}

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'Kubernetes/php/argo-rollout.yml'
          destination_repo: 'dmnemec/release-test'
          destination_folder: 'test-dir'
          user_email: 'example@email.com'
          user_name: 'dmnemec'
          commit_message: 'A custom message for the commit'